export interface CountrySeed {
  iso3: string;
  iso2: string;
  name: string;
  region: string;
  subRegion?: string;
  flag: string;
}

function flag(iso2: string): string {
  const upper = iso2.toUpperCase();
  return String.fromCodePoint(
    0x1f1e6 + upper.charCodeAt(0) - 65,
    0x1f1e6 + upper.charCodeAt(1) - 65
  );
}

export const COUNTRIES: CountrySeed[] = [
  // GCC
  { iso3: "ARE", iso2: "AE", name: "United Arab Emirates", region: "GCC", subRegion: "Gulf States", flag: flag("AE") },
  { iso3: "SAU", iso2: "SA", name: "Saudi Arabia", region: "GCC", subRegion: "Gulf States", flag: flag("SA") },
  { iso3: "QAT", iso2: "QA", name: "Qatar", region: "GCC", subRegion: "Gulf States", flag: flag("QA") },
  { iso3: "KWT", iso2: "KW", name: "Kuwait", region: "GCC", subRegion: "Gulf States", flag: flag("KW") },
  { iso3: "BHR", iso2: "BH", name: "Bahrain", region: "GCC", subRegion: "Gulf States", flag: flag("BH") },
  { iso3: "OMN", iso2: "OM", name: "Oman", region: "GCC", subRegion: "Gulf States", flag: flag("OM") },
  // MENA (non-GCC)
  { iso3: "EGY", iso2: "EG", name: "Egypt", region: "MENA", subRegion: "North Africa", flag: flag("EG") },
  { iso3: "JOR", iso2: "JO", name: "Jordan", region: "MENA", subRegion: "Levant", flag: flag("JO") },
  { iso3: "LBN", iso2: "LB", name: "Lebanon", region: "MENA", subRegion: "Levant", flag: flag("LB") },
  { iso3: "IRQ", iso2: "IQ", name: "Iraq", region: "MENA", subRegion: "Levant", flag: flag("IQ") },
  { iso3: "IRN", iso2: "IR", name: "Iran", region: "MENA", subRegion: "Western Asia", flag: flag("IR") },
  { iso3: "ISR", iso2: "IL", name: "Israel", region: "MENA", subRegion: "Levant", flag: flag("IL") },
  { iso3: "MAR", iso2: "MA", name: "Morocco", region: "MENA", subRegion: "North Africa", flag: flag("MA") },
  { iso3: "TUN", iso2: "TN", name: "Tunisia", region: "MENA", subRegion: "North Africa", flag: flag("TN") },
  { iso3: "DZA", iso2: "DZ", name: "Algeria", region: "MENA", subRegion: "North Africa", flag: flag("DZ") },
  { iso3: "LBY", iso2: "LY", name: "Libya", region: "MENA", subRegion: "North Africa", flag: flag("LY") },
  { iso3: "PSE", iso2: "PS", name: "Palestine", region: "MENA", subRegion: "Levant", flag: flag("PS") },
  { iso3: "SYR", iso2: "SY", name: "Syria", region: "MENA", subRegion: "Levant", flag: flag("SY") },
  { iso3: "YEM", iso2: "YE", name: "Yemen", region: "MENA", subRegion: "Arabian Peninsula", flag: flag("YE") },
  // Europe
  { iso3: "GBR", iso2: "GB", name: "United Kingdom", region: "Europe", subRegion: "Northern Europe", flag: flag("GB") },
  { iso3: "DEU", iso2: "DE", name: "Germany", region: "Europe", subRegion: "Western Europe", flag: flag("DE") },
  { iso3: "FRA", iso2: "FR", name: "France", region: "Europe", subRegion: "Western Europe", flag: flag("FR") },
  { iso3: "ITA", iso2: "IT", name: "Italy", region: "Europe", subRegion: "Southern Europe", flag: flag("IT") },
  { iso3: "ESP", iso2: "ES", name: "Spain", region: "Europe", subRegion: "Southern Europe", flag: flag("ES") },
  { iso3: "NLD", iso2: "NL", name: "Netherlands", region: "Europe", subRegion: "Western Europe", flag: flag("NL") },
  { iso3: "SWE", iso2: "SE", name: "Sweden", region: "Europe", subRegion: "Northern Europe", flag: flag("SE") },
  { iso3: "NOR", iso2: "NO", name: "Norway", region: "Europe", subRegion: "Northern Europe", flag: flag("NO") },
  { iso3: "DNK", iso2: "DK", name: "Denmark", region: "Europe", subRegion: "Northern Europe", flag: flag("DK") },
  { iso3: "FIN", iso2: "FI", name: "Finland", region: "Europe", subRegion: "Northern Europe", flag: flag("FI") },
  { iso3: "CHE", iso2: "CH", name: "Switzerland", region: "Europe", subRegion: "Western Europe", flag: flag("CH") },
  { iso3: "AUT", iso2: "AT", name: "Austria", region: "Europe", subRegion: "Western Europe", flag: flag("AT") },
  { iso3: "BEL", iso2: "BE", name: "Belgium", region: "Europe", subRegion: "Western Europe", flag: flag("BE") },
  { iso3: "IRL", iso2: "IE", name: "Ireland", region: "Europe", subRegion: "Northern Europe", flag: flag("IE") },
  { iso3: "PRT", iso2: "PT", name: "Portugal", region: "Europe", subRegion: "Southern Europe", flag: flag("PT") },
  { iso3: "GRC", iso2: "GR", name: "Greece", region: "Europe", subRegion: "Southern Europe", flag: flag("GR") },
  { iso3: "POL", iso2: "PL", name: "Poland", region: "Europe", subRegion: "Eastern Europe", flag: flag("PL") },
  { iso3: "CZE", iso2: "CZ", name: "Czech Republic", region: "Europe", subRegion: "Eastern Europe", flag: flag("CZ") },
  { iso3: "ROU", iso2: "RO", name: "Romania", region: "Europe", subRegion: "Eastern Europe", flag: flag("RO") },
  { iso3: "HUN", iso2: "HU", name: "Hungary", region: "Europe", subRegion: "Eastern Europe", flag: flag("HU") },
  { iso3: "BGR", iso2: "BG", name: "Bulgaria", region: "Europe", subRegion: "Eastern Europe", flag: flag("BG") },
  { iso3: "HRV", iso2: "HR", name: "Croatia", region: "Europe", subRegion: "Southern Europe", flag: flag("HR") },
  { iso3: "SVK", iso2: "SK", name: "Slovakia", region: "Europe", subRegion: "Eastern Europe", flag: flag("SK") },
  { iso3: "SVN", iso2: "SI", name: "Slovenia", region: "Europe", subRegion: "Southern Europe", flag: flag("SI") },
  { iso3: "LTU", iso2: "LT", name: "Lithuania", region: "Europe", subRegion: "Northern Europe", flag: flag("LT") },
  { iso3: "LVA", iso2: "LV", name: "Latvia", region: "Europe", subRegion: "Northern Europe", flag: flag("LV") },
  { iso3: "EST", iso2: "EE", name: "Estonia", region: "Europe", subRegion: "Northern Europe", flag: flag("EE") },
  { iso3: "LUX", iso2: "LU", name: "Luxembourg", region: "Europe", subRegion: "Western Europe", flag: flag("LU") },
  { iso3: "MLT", iso2: "MT", name: "Malta", region: "Europe", subRegion: "Southern Europe", flag: flag("MT") },
  { iso3: "CYP", iso2: "CY", name: "Cyprus", region: "Europe", subRegion: "Southern Europe", flag: flag("CY") },
  { iso3: "ISL", iso2: "IS", name: "Iceland", region: "Europe", subRegion: "Northern Europe", flag: flag("IS") },
  { iso3: "SRB", iso2: "RS", name: "Serbia", region: "Europe", subRegion: "Southern Europe", flag: flag("RS") },
  { iso3: "BIH", iso2: "BA", name: "Bosnia and Herzegovina", region: "Europe", subRegion: "Southern Europe", flag: flag("BA") },
  { iso3: "ALB", iso2: "AL", name: "Albania", region: "Europe", subRegion: "Southern Europe", flag: flag("AL") },
  { iso3: "MKD", iso2: "MK", name: "North Macedonia", region: "Europe", subRegion: "Southern Europe", flag: flag("MK") },
  { iso3: "MNE", iso2: "ME", name: "Montenegro", region: "Europe", subRegion: "Southern Europe", flag: flag("ME") },
  { iso3: "MDA", iso2: "MD", name: "Moldova", region: "Europe", subRegion: "Eastern Europe", flag: flag("MD") },
  { iso3: "UKR", iso2: "UA", name: "Ukraine", region: "Europe", subRegion: "Eastern Europe", flag: flag("UA") },
  { iso3: "BLR", iso2: "BY", name: "Belarus", region: "Europe", subRegion: "Eastern Europe", flag: flag("BY") },
  { iso3: "GEO", iso2: "GE", name: "Georgia", region: "Europe", subRegion: "Eastern Europe", flag: flag("GE") },
  { iso3: "ARM", iso2: "AM", name: "Armenia", region: "Europe", subRegion: "Eastern Europe", flag: flag("AM") },
  { iso3: "AZE", iso2: "AZ", name: "Azerbaijan", region: "Europe", subRegion: "Eastern Europe", flag: flag("AZ") },
  // North America
  { iso3: "USA", iso2: "US", name: "United States", region: "North America", flag: flag("US") },
  { iso3: "CAN", iso2: "CA", name: "Canada", region: "North America", flag: flag("CA") },
  { iso3: "MEX", iso2: "MX", name: "Mexico", region: "Latin America", subRegion: "Central America", flag: flag("MX") },
  // Latin America & Caribbean
  { iso3: "BRA", iso2: "BR", name: "Brazil", region: "Latin America", subRegion: "South America", flag: flag("BR") },
  { iso3: "ARG", iso2: "AR", name: "Argentina", region: "Latin America", subRegion: "South America", flag: flag("AR") },
  { iso3: "CHL", iso2: "CL", name: "Chile", region: "Latin America", subRegion: "South America", flag: flag("CL") },
  { iso3: "COL", iso2: "CO", name: "Colombia", region: "Latin America", subRegion: "South America", flag: flag("CO") },
  { iso3: "PER", iso2: "PE", name: "Peru", region: "Latin America", subRegion: "South America", flag: flag("PE") },
  { iso3: "VEN", iso2: "VE", name: "Venezuela", region: "Latin America", subRegion: "South America", flag: flag("VE") },
  { iso3: "ECU", iso2: "EC", name: "Ecuador", region: "Latin America", subRegion: "South America", flag: flag("EC") },
  { iso3: "BOL", iso2: "BO", name: "Bolivia", region: "Latin America", subRegion: "South America", flag: flag("BO") },
  { iso3: "PRY", iso2: "PY", name: "Paraguay", region: "Latin America", subRegion: "South America", flag: flag("PY") },
  { iso3: "URY", iso2: "UY", name: "Uruguay", region: "Latin America", subRegion: "South America", flag: flag("UY") },
  { iso3: "CRI", iso2: "CR", name: "Costa Rica", region: "Latin America", subRegion: "Central America", flag: flag("CR") },
  { iso3: "PAN", iso2: "PA", name: "Panama", region: "Latin America", subRegion: "Central America", flag: flag("PA") },
  { iso3: "DOM", iso2: "DO", name: "Dominican Republic", region: "Latin America", subRegion: "Caribbean", flag: flag("DO") },
  { iso3: "GTM", iso2: "GT", name: "Guatemala", region: "Latin America", subRegion: "Central America", flag: flag("GT") },
  { iso3: "HND", iso2: "HN", name: "Honduras", region: "Latin America", subRegion: "Central America", flag: flag("HN") },
  { iso3: "SLV", iso2: "SV", name: "El Salvador", region: "Latin America", subRegion: "Central America", flag: flag("SV") },
  { iso3: "NIC", iso2: "NI", name: "Nicaragua", region: "Latin America", subRegion: "Central America", flag: flag("NI") },
  { iso3: "CUB", iso2: "CU", name: "Cuba", region: "Latin America", subRegion: "Caribbean", flag: flag("CU") },
  { iso3: "JAM", iso2: "JM", name: "Jamaica", region: "Latin America", subRegion: "Caribbean", flag: flag("JM") },
  { iso3: "TTO", iso2: "TT", name: "Trinidad and Tobago", region: "Latin America", subRegion: "Caribbean", flag: flag("TT") },
  // Asia-Pacific
  { iso3: "CHN", iso2: "CN", name: "China", region: "Asia-Pacific", subRegion: "East Asia", flag: flag("CN") },
  { iso3: "JPN", iso2: "JP", name: "Japan", region: "Asia-Pacific", subRegion: "East Asia", flag: flag("JP") },
  { iso3: "KOR", iso2: "KR", name: "South Korea", region: "Asia-Pacific", subRegion: "East Asia", flag: flag("KR") },
  { iso3: "IND", iso2: "IN", name: "India", region: "Asia-Pacific", subRegion: "South Asia", flag: flag("IN") },
  { iso3: "IDN", iso2: "ID", name: "Indonesia", region: "Asia-Pacific", subRegion: "Southeast Asia", flag: flag("ID") },
  { iso3: "THA", iso2: "TH", name: "Thailand", region: "Asia-Pacific", subRegion: "Southeast Asia", flag: flag("TH") },
  { iso3: "VNM", iso2: "VN", name: "Vietnam", region: "Asia-Pacific", subRegion: "Southeast Asia", flag: flag("VN") },
  { iso3: "PHL", iso2: "PH", name: "Philippines", region: "Asia-Pacific", subRegion: "Southeast Asia", flag: flag("PH") },
  { iso3: "MYS", iso2: "MY", name: "Malaysia", region: "Asia-Pacific", subRegion: "Southeast Asia", flag: flag("MY") },
  { iso3: "SGP", iso2: "SG", name: "Singapore", region: "Asia-Pacific", subRegion: "Southeast Asia", flag: flag("SG") },
  { iso3: "AUS", iso2: "AU", name: "Australia", region: "Asia-Pacific", subRegion: "Oceania", flag: flag("AU") },
  { iso3: "NZL", iso2: "NZ", name: "New Zealand", region: "Asia-Pacific", subRegion: "Oceania", flag: flag("NZ") },
  { iso3: "PAK", iso2: "PK", name: "Pakistan", region: "Asia-Pacific", subRegion: "South Asia", flag: flag("PK") },
  { iso3: "BGD", iso2: "BD", name: "Bangladesh", region: "Asia-Pacific", subRegion: "South Asia", flag: flag("BD") },
  { iso3: "LKA", iso2: "LK", name: "Sri Lanka", region: "Asia-Pacific", subRegion: "South Asia", flag: flag("LK") },
  { iso3: "NPL", iso2: "NP", name: "Nepal", region: "Asia-Pacific", subRegion: "South Asia", flag: flag("NP") },
  { iso3: "MMR", iso2: "MM", name: "Myanmar", region: "Asia-Pacific", subRegion: "Southeast Asia", flag: flag("MM") },
  { iso3: "KHM", iso2: "KH", name: "Cambodia", region: "Asia-Pacific", subRegion: "Southeast Asia", flag: flag("KH") },
  { iso3: "LAO", iso2: "LA", name: "Laos", region: "Asia-Pacific", subRegion: "Southeast Asia", flag: flag("LA") },
  { iso3: "MNG", iso2: "MN", name: "Mongolia", region: "Asia-Pacific", subRegion: "East Asia", flag: flag("MN") },
  { iso3: "TWN", iso2: "TW", name: "Taiwan", region: "Asia-Pacific", subRegion: "East Asia", flag: flag("TW") },
  { iso3: "HKG", iso2: "HK", name: "Hong Kong", region: "Asia-Pacific", subRegion: "East Asia", flag: flag("HK") },
  { iso3: "FJI", iso2: "FJ", name: "Fiji", region: "Asia-Pacific", subRegion: "Oceania", flag: flag("FJ") },
  { iso3: "PNG", iso2: "PG", name: "Papua New Guinea", region: "Asia-Pacific", subRegion: "Oceania", flag: flag("PG") },
  // Central Asia
  { iso3: "KAZ", iso2: "KZ", name: "Kazakhstan", region: "Central Asia", flag: flag("KZ") },
  { iso3: "UZB", iso2: "UZ", name: "Uzbekistan", region: "Central Asia", flag: flag("UZ") },
  { iso3: "TKM", iso2: "TM", name: "Turkmenistan", region: "Central Asia", flag: flag("TM") },
  { iso3: "TJK", iso2: "TJ", name: "Tajikistan", region: "Central Asia", flag: flag("TJ") },
  { iso3: "KGZ", iso2: "KG", name: "Kyrgyzstan", region: "Central Asia", flag: flag("KG") },
  { iso3: "AFG", iso2: "AF", name: "Afghanistan", region: "Central Asia", flag: flag("AF") },
  // Russia
  { iso3: "RUS", iso2: "RU", name: "Russia", region: "Europe", subRegion: "Eastern Europe", flag: flag("RU") },
  { iso3: "TUR", iso2: "TR", name: "Turkey", region: "Europe", subRegion: "Southern Europe", flag: flag("TR") },
  // Sub-Saharan Africa
  { iso3: "ZAF", iso2: "ZA", name: "South Africa", region: "Sub-Saharan Africa", subRegion: "Southern Africa", flag: flag("ZA") },
  { iso3: "NGA", iso2: "NG", name: "Nigeria", region: "Sub-Saharan Africa", subRegion: "West Africa", flag: flag("NG") },
  { iso3: "KEN", iso2: "KE", name: "Kenya", region: "Sub-Saharan Africa", subRegion: "East Africa", flag: flag("KE") },
  { iso3: "ETH", iso2: "ET", name: "Ethiopia", region: "Sub-Saharan Africa", subRegion: "East Africa", flag: flag("ET") },
  { iso3: "GHA", iso2: "GH", name: "Ghana", region: "Sub-Saharan Africa", subRegion: "West Africa", flag: flag("GH") },
  { iso3: "TZA", iso2: "TZ", name: "Tanzania", region: "Sub-Saharan Africa", subRegion: "East Africa", flag: flag("TZ") },
  { iso3: "UGA", iso2: "UG", name: "Uganda", region: "Sub-Saharan Africa", subRegion: "East Africa", flag: flag("UG") },
  { iso3: "SEN", iso2: "SN", name: "Senegal", region: "Sub-Saharan Africa", subRegion: "West Africa", flag: flag("SN") },
  { iso3: "CIV", iso2: "CI", name: "Ivory Coast", region: "Sub-Saharan Africa", subRegion: "West Africa", flag: flag("CI") },
  { iso3: "CMR", iso2: "CM", name: "Cameroon", region: "Sub-Saharan Africa", subRegion: "Central Africa", flag: flag("CM") },
  { iso3: "COD", iso2: "CD", name: "DR Congo", region: "Sub-Saharan Africa", subRegion: "Central Africa", flag: flag("CD") },
  { iso3: "AGO", iso2: "AO", name: "Angola", region: "Sub-Saharan Africa", subRegion: "Southern Africa", flag: flag("AO") },
  { iso3: "MOZ", iso2: "MZ", name: "Mozambique", region: "Sub-Saharan Africa", subRegion: "Southern Africa", flag: flag("MZ") },
  { iso3: "MDG", iso2: "MG", name: "Madagascar", region: "Sub-Saharan Africa", subRegion: "East Africa", flag: flag("MG") },
  { iso3: "ZMB", iso2: "ZM", name: "Zambia", region: "Sub-Saharan Africa", subRegion: "Southern Africa", flag: flag("ZM") },
  { iso3: "ZWE", iso2: "ZW", name: "Zimbabwe", region: "Sub-Saharan Africa", subRegion: "Southern Africa", flag: flag("ZW") },
  { iso3: "MWI", iso2: "MW", name: "Malawi", region: "Sub-Saharan Africa", subRegion: "Southern Africa", flag: flag("MW") },
  { iso3: "RWA", iso2: "RW", name: "Rwanda", region: "Sub-Saharan Africa", subRegion: "East Africa", flag: flag("RW") },
  { iso3: "MLI", iso2: "ML", name: "Mali", region: "Sub-Saharan Africa", subRegion: "West Africa", flag: flag("ML") },
  { iso3: "BFA", iso2: "BF", name: "Burkina Faso", region: "Sub-Saharan Africa", subRegion: "West Africa", flag: flag("BF") },
  { iso3: "NER", iso2: "NE", name: "Niger", region: "Sub-Saharan Africa", subRegion: "West Africa", flag: flag("NE") },
  { iso3: "TCD", iso2: "TD", name: "Chad", region: "Sub-Saharan Africa", subRegion: "Central Africa", flag: flag("TD") },
  { iso3: "SDN", iso2: "SD", name: "Sudan", region: "Sub-Saharan Africa", subRegion: "East Africa", flag: flag("SD") },
  { iso3: "SSD", iso2: "SS", name: "South Sudan", region: "Sub-Saharan Africa", subRegion: "East Africa", flag: flag("SS") },
  { iso3: "SOM", iso2: "SO", name: "Somalia", region: "Sub-Saharan Africa", subRegion: "East Africa", flag: flag("SO") },
  { iso3: "BEN", iso2: "BJ", name: "Benin", region: "Sub-Saharan Africa", subRegion: "West Africa", flag: flag("BJ") },
  { iso3: "TGO", iso2: "TG", name: "Togo", region: "Sub-Saharan Africa", subRegion: "West Africa", flag: flag("TG") },
  { iso3: "SLE", iso2: "SL", name: "Sierra Leone", region: "Sub-Saharan Africa", subRegion: "West Africa", flag: flag("SL") },
  { iso3: "LBR", iso2: "LR", name: "Liberia", region: "Sub-Saharan Africa", subRegion: "West Africa", flag: flag("LR") },
  { iso3: "MRT", iso2: "MR", name: "Mauritania", region: "Sub-Saharan Africa", subRegion: "West Africa", flag: flag("MR") },
  { iso3: "ERI", iso2: "ER", name: "Eritrea", region: "Sub-Saharan Africa", subRegion: "East Africa", flag: flag("ER") },
  { iso3: "GMB", iso2: "GM", name: "Gambia", region: "Sub-Saharan Africa", subRegion: "West Africa", flag: flag("GM") },
  { iso3: "BWA", iso2: "BW", name: "Botswana", region: "Sub-Saharan Africa", subRegion: "Southern Africa", flag: flag("BW") },
  { iso3: "NAM", iso2: "NA", name: "Namibia", region: "Sub-Saharan Africa", subRegion: "Southern Africa", flag: flag("NA") },
  { iso3: "GAB", iso2: "GA", name: "Gabon", region: "Sub-Saharan Africa", subRegion: "Central Africa", flag: flag("GA") },
  { iso3: "LSO", iso2: "LS", name: "Lesotho", region: "Sub-Saharan Africa", subRegion: "Southern Africa", flag: flag("LS") },
  { iso3: "SWZ", iso2: "SZ", name: "Eswatini", region: "Sub-Saharan Africa", subRegion: "Southern Africa", flag: flag("SZ") },
  { iso3: "MUS", iso2: "MU", name: "Mauritius", region: "Sub-Saharan Africa", subRegion: "East Africa", flag: flag("MU") },
  { iso3: "GNB", iso2: "GW", name: "Guinea-Bissau", region: "Sub-Saharan Africa", subRegion: "West Africa", flag: flag("GW") },
  { iso3: "GIN", iso2: "GN", name: "Guinea", region: "Sub-Saharan Africa", subRegion: "West Africa", flag: flag("GN") },
  { iso3: "COG", iso2: "CG", name: "Republic of Congo", region: "Sub-Saharan Africa", subRegion: "Central Africa", flag: flag("CG") },
  { iso3: "CAF", iso2: "CF", name: "Central African Republic", region: "Sub-Saharan Africa", subRegion: "Central Africa", flag: flag("CF") },
  { iso3: "GNQ", iso2: "GQ", name: "Equatorial Guinea", region: "Sub-Saharan Africa", subRegion: "Central Africa", flag: flag("GQ") },
  { iso3: "DJI", iso2: "DJ", name: "Djibouti", region: "Sub-Saharan Africa", subRegion: "East Africa", flag: flag("DJ") },
  { iso3: "CPV", iso2: "CV", name: "Cape Verde", region: "Sub-Saharan Africa", subRegion: "West Africa", flag: flag("CV") },
  { iso3: "STP", iso2: "ST", name: "Sao Tome and Principe", region: "Sub-Saharan Africa", subRegion: "Central Africa", flag: flag("ST") },
  { iso3: "COM", iso2: "KM", name: "Comoros", region: "Sub-Saharan Africa", subRegion: "East Africa", flag: flag("KM") },
  { iso3: "SYC", iso2: "SC", name: "Seychelles", region: "Sub-Saharan Africa", subRegion: "East Africa", flag: flag("SC") },
  { iso3: "BDI", iso2: "BI", name: "Burundi", region: "Sub-Saharan Africa", subRegion: "East Africa", flag: flag("BI") },
  // ── UN member states added to reach 193 (plus non-UN observers PSE, TWN, HKG above) ──
  // Europe — microstates
  { iso3: "AND", iso2: "AD", name: "Andorra", region: "Europe", subRegion: "Southern Europe", flag: flag("AD") },
  { iso3: "MCO", iso2: "MC", name: "Monaco", region: "Europe", subRegion: "Western Europe", flag: flag("MC") },
  { iso3: "SMR", iso2: "SM", name: "San Marino", region: "Europe", subRegion: "Southern Europe", flag: flag("SM") },
  { iso3: "LIE", iso2: "LI", name: "Liechtenstein", region: "Europe", subRegion: "Western Europe", flag: flag("LI") },
  // Caribbean & Latin America
  { iso3: "ATG", iso2: "AG", name: "Antigua and Barbuda", region: "Latin America", subRegion: "Caribbean", flag: flag("AG") },
  { iso3: "BHS", iso2: "BS", name: "Bahamas", region: "Latin America", subRegion: "Caribbean", flag: flag("BS") },
  { iso3: "BRB", iso2: "BB", name: "Barbados", region: "Latin America", subRegion: "Caribbean", flag: flag("BB") },
  { iso3: "BLZ", iso2: "BZ", name: "Belize", region: "Latin America", subRegion: "Central America", flag: flag("BZ") },
  { iso3: "DMA", iso2: "DM", name: "Dominica", region: "Latin America", subRegion: "Caribbean", flag: flag("DM") },
  { iso3: "GRD", iso2: "GD", name: "Grenada", region: "Latin America", subRegion: "Caribbean", flag: flag("GD") },
  { iso3: "GUY", iso2: "GY", name: "Guyana", region: "Latin America", subRegion: "South America", flag: flag("GY") },
  { iso3: "HTI", iso2: "HT", name: "Haiti", region: "Latin America", subRegion: "Caribbean", flag: flag("HT") },
  { iso3: "KNA", iso2: "KN", name: "Saint Kitts and Nevis", region: "Latin America", subRegion: "Caribbean", flag: flag("KN") },
  { iso3: "LCA", iso2: "LC", name: "Saint Lucia", region: "Latin America", subRegion: "Caribbean", flag: flag("LC") },
  { iso3: "VCT", iso2: "VC", name: "Saint Vincent and the Grenadines", region: "Latin America", subRegion: "Caribbean", flag: flag("VC") },
  { iso3: "SUR", iso2: "SR", name: "Suriname", region: "Latin America", subRegion: "South America", flag: flag("SR") },
  // Asia
  { iso3: "BTN", iso2: "BT", name: "Bhutan", region: "Asia-Pacific", subRegion: "South Asia", flag: flag("BT") },
  { iso3: "BRN", iso2: "BN", name: "Brunei", region: "Asia-Pacific", subRegion: "Southeast Asia", flag: flag("BN") },
  { iso3: "MDV", iso2: "MV", name: "Maldives", region: "Asia-Pacific", subRegion: "South Asia", flag: flag("MV") },
  { iso3: "PRK", iso2: "KP", name: "North Korea", region: "Asia-Pacific", subRegion: "East Asia", flag: flag("KP") },
  { iso3: "TLS", iso2: "TL", name: "Timor-Leste", region: "Asia-Pacific", subRegion: "Southeast Asia", flag: flag("TL") },
  // Pacific
  { iso3: "KIR", iso2: "KI", name: "Kiribati", region: "Asia-Pacific", subRegion: "Oceania", flag: flag("KI") },
  { iso3: "MHL", iso2: "MH", name: "Marshall Islands", region: "Asia-Pacific", subRegion: "Oceania", flag: flag("MH") },
  { iso3: "FSM", iso2: "FM", name: "Micronesia", region: "Asia-Pacific", subRegion: "Oceania", flag: flag("FM") },
  { iso3: "NRU", iso2: "NR", name: "Nauru", region: "Asia-Pacific", subRegion: "Oceania", flag: flag("NR") },
  { iso3: "PLW", iso2: "PW", name: "Palau", region: "Asia-Pacific", subRegion: "Oceania", flag: flag("PW") },
  { iso3: "WSM", iso2: "WS", name: "Samoa", region: "Asia-Pacific", subRegion: "Oceania", flag: flag("WS") },
  { iso3: "SLB", iso2: "SB", name: "Solomon Islands", region: "Asia-Pacific", subRegion: "Oceania", flag: flag("SB") },
  { iso3: "TON", iso2: "TO", name: "Tonga", region: "Asia-Pacific", subRegion: "Oceania", flag: flag("TO") },
  { iso3: "TUV", iso2: "TV", name: "Tuvalu", region: "Asia-Pacific", subRegion: "Oceania", flag: flag("TV") },
  { iso3: "VUT", iso2: "VU", name: "Vanuatu", region: "Asia-Pacific", subRegion: "Oceania", flag: flag("VU") },
];

export const SCORING_DIMENSIONS = [
  { dimension: "digital-maturity", description: "Digital transformation maturity of the social security system" },
  { dimension: "service-breadth", description: "Range and depth of services offered to beneficiaries" },
  { dimension: "customer-experience", description: "Quality of citizen-facing service delivery and UX" },
  { dimension: "operational-efficiency", description: "Internal process efficiency and cost management" },
  { dimension: "innovation", description: "Adoption of emerging technologies and innovative practices" },
  { dimension: "governance-compliance", description: "Regulatory compliance and governance framework strength" },
  { dimension: "data-analytics", description: "Data-driven decision making and analytics capability" },
  { dimension: "channel-strategy", description: "Multi-channel service delivery strategy and execution" },
];
